# Single source of truth for chapters, merge chains and item descriptions.
# Two of an item make the next one. Chain ends merge into the chapter's ★.
# Descriptions are shown in LOOP 2 ONLY. Loop 1 shows the item name + merge path.

CHAPTERS = [
dict(
  key="tut", num="Tutorial", title="The Worm", time=15, stage="Stage 1", color="teal",
  story=[
    "A black screen and a handful of glowing cells. You drag one onto another, and they connect. You keep going until the pieces become a small, simple, living thing. Nobody tells you what it is.",
    "A counter in the top panel climbs as you merge and lands on <strong>302</strong> when the worm is finished.",
  ],
  tracks=[dict(code="00", tag="worm", title="The Worm", items=[
    ("Neuron", "one cell that carries a signal. alone, it can't do anything."),
    ("Neuron Pair", "two neurons touching. the gap between them is a synapse. the worm has about 7,000 of these. you have around 100 trillion."),
    ("Nerve Bundle", "neurons wired together. touch the worm's nose and this is what makes it back away."),
    ("Nerve Ring", "the worm's brain is a ring wrapped around its throat. everything it knows passes through here."),
  ])],
  final=("The Worm ★", "Nerve Ring + Nerve Ring",
         "c. elegans. one millimeter long. 302 neurons, every one mapped. in 2014 its wiring was loaded into a lego robot, and the robot moved like a worm."),
  companion="In the corner of the top panel with its <strong>eye closed</strong>. It breathes slowly, like something sleeping, and its traces pulse dimly about once every four seconds.",
  mechanic="The generator gives exactly 16 neurons in Loop 1. They pair off perfectly: 16 → 8 → 4 → 2 → 1 worm, with nothing left over. <strong>From Loop 2 on it gives 17.</strong> See section 04.",
),
dict(
  key="c1", num="Ch1", title="The Big Bang", time=30, stage="Stage 1", color="teal",
  story=[
    "A flash, and then everything. Sparks become atoms, atoms become clouds, clouds light up into stars, and the stars gather into a galaxy. Meanwhile dust clumps into rock, and rock into a planet. It's the whole universe in one board, and every icon should read at a glance: spark, atom, cloud, star, spiral.",
  ],
  tracks=[
    dict(code="01a", tag="stars", title="Stars", items=[
      ("Spark", "13.8 billion years ago, everything that exists came out of a single point. nobody knows what came before, or if 'before' even means anything."),
      ("Atom", "the first atoms were almost all hydrogen, the simplest kind. about three quarters of ordinary matter still is."),
      ("Gas Cloud", "hydrogen drifting in the dark until gravity pulls it into a clump."),
      ("Star", "an explosion held together by its own gravity. it cooks hydrogen into heavier atoms."),
      ("Galaxy", "a hundred billion stars or more, turning together. there are hundreds of billions of galaxies."),
    ]),
    dict(code="01b", tag="planet", title="The Planet", items=[
      ("Dust", "the iron in your blood and the calcium in your bones came from stars that exploded before the sun was born."),
      ("Rock", "dust sticks to dust. then rock hits rock, for millions of years."),
      ("Planet", "a new world, red-hot from every collision. one of those collisions knocked loose the moon."),
      ("Earth", "the right distance from its star for water to stay liquid."),
    ]),
  ],
  final=("Pale Blue Dot ★", "Galaxy + Earth",
         "in 1990, voyager 1 turned around and photographed earth from six billion kilometers away. it's smaller than a pixel. everyone who has ever lived is in that pixel."),
  companion="Eye closed.",
  facts=[("violet", "Loop 2 only — companion note, when the first Star appears",
    "<span class='mono'>\"Vitaly Vanchurin published a mathematical model in which the universe's fundamental variables interact the way neurons do. Connections. Weights. Learning. Under certain conditions, his math produces quantum mechanics. Under others, gravity. He called it speculative.\"<br><span class='dim'>[pause]</span><br>\"He didn't say it was wrong.\"</span>")],
),
dict(
  key="c2", num="Ch2", title="Life", time=35, stage="Stage 2", color="teal",
  story=[
    "Life starts as a single cell in the sea and keeps going: jellyfish, trilobites, fish, lizards, dinosaurs. On a second track, eyes evolve: a spot, a cup, an eyeball. At the end the two tracks meet, and the chapter's ★ is a huge ancient eye. The world is being watched now.",
    "The science holds up. The first eyes opened in the Cambrian, 541 million years ago, and by the time of the dinosaurs the world had been watched for 300 million years. The ★ just shows it in one picture.",
  ],
  tracks=[
    dict(code="02a", tag="life", title="Life", items=[
      ("Cell", "every living thing that has ever existed descends from one of these."),
      ("Jellyfish", "no brain, no heart, no bones. jellyfish have been drifting for more than 500 million years."),
      ("Trilobite", "its eyes had lenses made of crystal. it saw the world through stone."),
      ("Fish", "everything with a backbone, including you, started as one of these."),
      ("Lizard", "an egg with a shell meant life could finally leave the water for good."),
      ("Dinosaur", "they ruled for 165 million years. tyrannosaurus lived closer in time to you than to stegosaurus."),
    ]),
    dict(code="02b", tag="sight", title="Sight", items=[
      ("Eye Spot", "a patch of cells that can tell light from dark. that's all. that's everything."),
      ("Eye Cup", "fold the patch inward and now it knows which direction the light came from."),
      ("Eyeball", "add a lens and the world comes into focus. eyes evolved on their own more than 40 separate times."),
    ]),
  ],
  final=("The Eye ★", "Dinosaur + Eyeball",
         "541 million years ago, the first eyes opened. by the time of the dinosaurs, the world had been watched for 300 million years. it has never stopped."),
  companion="Eye closed. When The Eye ★ forms, the companion's traces flare once, briefly. <strong>The companion's eye is drawn at exactly the size of The Eye ★ tile.</strong>",
  facts=[("violet", "Loop 2 only — companion note, when The Eye ★ forms",
    "<span class='mono'>\"in quantum mechanics, measuring something changes it. physicists still argue about what counts as a measurement.\"<br><span class='dim'>[pause]</span><br>\"does an eye?\"</span>")],
),
dict(
  key="c3", num="Ch3", title="After the Asteroid", time=25, stage="Stage 2", color="teal",
  story=[
    "Short and brutal. An asteroid, a fireball, a crater, and a sky full of ash. The dinosaurs are gone. The survivors are small and furry and live underground. Given time, they climb trees, come back down, and one of them stands up.",
    "The final merge is ash plus an ape, and the ★ is a footprint pressed into ash. It really happened.",
  ],
  tracks=[
    dict(code="03a", tag="the end", title="The End", items=[
      ("Asteroid", "ten kilometers wide. its orbit and ours were always going to meet."),
      ("Fireball", "about twenty kilometers per second. it crossed the sky in seconds."),
      ("Crater", "180 kilometers wide, buried under mexico. three out of four species didn't survive what came next."),
      ("Ash Cloud", "soot blocked the sun for years. the world went dark and cold."),
    ]),
    dict(code="03b", tag="survivors", title="The Survivors", items=[
      ("Mouse", "the mammals that survived were small. they lived underground and came out at night."),
      ("Lemur", "hands that grip. eyes that face forward."),
      ("Monkey", "a bigger brain, a longer childhood, a family."),
      ("Ape", "no tail. around seven million years ago, one line of apes started walking on two legs."),
    ]),
  ],
  final=("Footprint ★", "Ash Cloud + Ape",
         "3.66 million years ago, two people walked across fresh volcanic ash in tanzania. rain set it like cement. their footprints are still there."),
  props=[("Mammoth", ""), ("Saber-Tooth", ""), ("Dinosaur Skull", "")],
  companion="Eye closed. After the Crater, the board goes dark, and <strong>for three seconds its traces go dark too</strong>. It's the only time the corner is completely empty. As the ash settles it turns to snow, and mammoths start wandering through the background.",
),
dict(
  key="c4", num="Ch4", title="The Cavemen", time=40, stage="Stage 3", color="amber",
  story=[
    "Two things happen on the same board: one person grows up, and a people learn what they can do. The ★ is a handprint on a cave wall, the first time anyone left a mark on purpose.",
  ],
  tracks=[
    dict(code="04a", tag="a life", title="A Life", items=[
      ("Baby", "human babies are born more helpless than almost any other animal. someone has to stay."),
      ("Child", "learns everything by copying. watch what you teach it."),
      ("Teen", "a brain rewiring itself. it won't finish until around 25."),
      ("Adult", "hunts, gathers, carries, remembers where the water is."),
      ("Elder", "for most of history, the oldest person alive was the whole library."),
    ]),
    dict(code="04b", tag="discovery", title="Discovery", items=[
      ("Stone Tool", "3.3 million years old, older than our species. someone hit a rock with a rock, on purpose."),
      ("Flint", "strike it against the right stone and you get a spark."),
      ("Fire", "cooked food is easier to digest. some scientists think fire is why our brains got so big."),
      ("Spear", "now we could hunt things bigger than us."),
      ("Bone Needle", "clothes. which meant cold places. which meant everywhere."),
      ("Cave Painting", "animals in ochre and charcoal, painted by firelight deep inside a cave."),
    ]),
  ],
  final=("Handprint ★", "Elder + Cave Painting",
         "paint blown around a hand pressed to a cave wall, tens of thousands of years ago. it means: i was here."),
  companion="Eye closed.",
),
dict(
  key="c5", num="Ch5", title="The Inventors", time=35, stage="Stage 3", color="amber",
  story=[
    "Centuries compress. Every invention makes the next one possible. One track is power and the other is words, and where they meet is a tiny switch that runs everything after it.",
  ],
  tracks=[
    dict(code="05a", tag="power", title="Power", items=[
      ("Wheel", "about 5,500 years ago. first for pottery. then someone turned it on its side."),
      ("Water Wheel", "the river does the work now."),
      ("Steam Engine", "boil water, push a piston, change the world."),
      ("Kite", "1752. ben franklin flew a kite into a storm to prove lightning was electricity."),
      ("Lightbulb", "edison's team tested thousands of materials. the one that lasted 1,200 hours was bamboo."),
    ]),
    dict(code="05b", tag="words", title="Words", items=[
      ("Clay Tablet", "writing was invented to keep track of grain and debt. poetry came later."),
      ("Printing Press", "around 1440. ideas stopped dying with the people who had them."),
      ("Telegraph", "1844: 'what hath god wrought.' a message that outran a horse."),
      ("Telephone", "a voice turned into electricity and back. 'mr. watson, come here, i want to see you.'"),
      ("Radio", "voices through the air. the earliest broadcasts are still traveling out into space."),
    ]),
  ],
  final=("The Transistor ★", "Lightbulb + Radio",
         "1947. a switch with no moving parts. it only works because of quantum mechanics. there are billions of them in the phone in your hand."),
  companion="Eye closed.",
),
dict(
  key="c6", num="Ch6", title="The City", time=45, stage="Stage 3–4", color="amber",
  story=[
    "On one track a hut becomes a city. On the other, people learn to move faster, then higher, then off the planet. From above, the finished board looks exactly like a circuit board. The chapter ends with a building full of machines that remember everything.",
  ],
  tracks=[
    dict(code="06a", tag="city", title="The City", items=[
      ("Hut", "four walls and a roof. the first time a place was yours."),
      ("House", "farming meant staying. staying meant building something that would last."),
      ("Village", "a few families. everyone knows everyone."),
      ("Town", "a market, a wall, someone in charge."),
      ("City", "uruk, 5,000 years ago. the first time that many strangers had to live together."),
      ("Skyscraper", "steel frames and the elevator made up possible."),
      ("Metropolis", "more than half of all humans live in cities now. from above at night, they look like circuitry."),
    ]),
    dict(code="06b", tag="motion", title="Motion", items=[
      ("Horse & Buggy", "for all of history, nothing on land moved faster than a horse."),
      ("Train", "railroads made the world agree on what time it was."),
      ("Car", "freedom, traffic, the suburbs, the smell of gasoline."),
      ("Airplane", "1903. twelve seconds in the air. sixty-six years later, people walked on the moon."),
      ("Rocket", "to leave the earth you have to go about eleven kilometers per second."),
      ("Satellite", "thousands of them overhead right now. one of them is telling your phone where you are."),
    ]),
  ],
  final=("Data Center ★", "Metropolis + Satellite",
         "rooms full of machines holding everything we've written, posted and searched. they never sleep. some use as much electricity as a small city."),
  companion="Eye closed. When Data Center ★ is made, the traces on the board and the traces on the companion pulse together, once.",
),
dict(
  key="c7", num="Ch7", title="Millennial Childhood", time=55, stage="Stage 4", color="amber",
  story=[
    "The board turns into a childhood: a baby bottle, crayons, a lunchbox, a school bus. It also has a <strong>Toy Box</strong> track of Trolls, Poochi, Furby, Tamagotchi, and consoles. A player of the right age will feel it in their chest before they know what they're looking at.",
    "This board should feel like too much, because childhood does when you look back at it. Somewhere in the middle of it, there's a kitten.",
  ],
  tracks=[
    dict(code="07a", tag="growing up", title="Growing Up", items=[
      ("Baby Bottle", "a newborn can only focus about 25 centimeters away. just far enough to see the face holding them."),
      ("Pacifier", "comfort you can hold in your mouth. you'll look for it in other shapes for the rest of your life."),
      ("Building Blocks", "stack, knock down, stack again. the first physics you ever did."),
      ("Crayons", "the 64-box with the sharpener built into the back."),
      ("Lunchbox", "a metal box with a cartoon on the lid and a thermos that always leaked."),
      ("School Bus", "the same seat every morning. the smell of vinyl and rain."),
      ("Backpack", "everything important, on your back, every day."),
    ]),
    dict(code="07b", tag="toy box", title="The Toy Box", items=[
      ("Trolls Doll", "first carved by a danish woodcarver in 1959. the neon hair came later."),
      ("Poochi", "a toy dog that was never going to die. you checked on it anyway."),
      ("Furby", "it seemed to learn english the more you talked to it. it didn't. it was programmed to seem like it did."),
      ("Tamagotchi", "a pet that lived on a keychain. if you forgot to feed it, it died. then you pressed reset."),
      ("Game Boy", "1989. a grey brick, four AA batteries, and a whole world in green."),
      ("Nintendo 64", "four controller ports. everyone in the same room, playing the same game."),
      ("PlayStation", "the memory card held fifteen blocks. you chose which ones to keep."),
    ]),
    dict(code="07c", tag="cat", title="The Kitten", items=[
      ("Paw Print", "you didn't tap for this."),
      ("Kitten", "a kitten's eyes stay closed for the first week or two. then they open."),
    ]),
  ],
  extra_final=("Cat", "Kitten + Kitten",
         "in 1935, a physicist imagined a cat sealed in a box, alive and dead at the same time until someone looks. you looked."),
  final=("Home Video ★", "Backpack + PlayStation",
         "a tape labeled in marker. the tv is on, the cat is on the rug, and somebody is laughing off-camera."),
  companion="Eye closed until the cat. A <strong>Paw Print</strong> appears that nobody tapped for, and one of the companion's cables twitches as it lands. From then on the generator mixes in more Paw Prints. Two make a Kitten, and two Kittens make a <strong>Cat</strong>. The chapter can't end until the Cat exists. <strong>The moment the Cat is made, the companion's eye snaps open.</strong> There's no fade: it cuts from closed to open, looking straight at the player, with one short vibration. The board carries on as if nothing happened. From then on its eye follows whatever you tap.",
  facts=[("violet", "Why the cat opens the eye",
    "Schrödinger's cat: a cat in a sealed box that's alive and dead at the same time until someone looks. The companion has been sealed shut since the first second of the game. The player makes a cat, looks at it, and something is observed into being. In Loop 1 nobody explains it. In Loop 2 the Cat's description does.")],
),
dict(
  key="c8", num="Ch8", title="The Feed", time=45, stage="Stage 4", color="red",
  story=[
    "The kid grows up into a screen. The first track is every device that ever lived in your pocket, ending in the news. The second track is everything that piles up while you're looking at it. Both generate faster than anywhere else in the game. The player may feel like they can't keep up. They're not supposed to.",
    "The ★ is a phone with a shattered screen.",
  ],
  tracks=[
    dict(code="08a", tag="screen", title="The Screen", items=[
      ("Old Mac", "a beige box and a startup chime. the first machine in the house that talked back."),
      ("Floppy Disk", "1.44 megabytes. it's still the save icon."),
      ("CD", "a laser reads tiny pits along a spiral. seventy-four minutes of music."),
      ("Flip Phone", "snake. t9. snapping it shut to hang up on someone."),
      ("Smartphone", "2007. the internet in your pocket. you'll touch it thousands of times a day."),
      ("Notification", "a red dot. your brain treats it like something might be wrong."),
      ("AI Chatbot", "a machine that writes and talks back. everyone's asking what it means. so is it."),
      ("Breaking News", "something terrible happened somewhere. it will happen again tomorrow."),
    ]),
    dict(code="08b", tag="weight", title="The Weight", items=[
      ("Missed Call (Mom)", "you'll call her back."),
      ("Overdue Bill", "red text. you already knew."),
      ("Pill Bottle", "it helps. it's supposed to."),
      ("Unread Emails", "999+. you stopped opening them. they didn't stop coming."),
      ("Layoff Email", "a calendar invite with no agenda."),
      ("Eviction Notice", "taped to the door where the whole hallway can read it."),
      ("Tissue Box", "kept in the car. for the parking lot, before you go inside."),
    ]),
  ],
  final=("Cracked Screen ★", "Breaking News + Tissue Box",
         "the world and the weight, at the same time. something had to give."),
  companion="Eye open. It flicks to every new item the instant it lands, a little too fast.",
),
dict(
  key="c9", num="Ch9", title="Pandemic", time=40, stage="Stage 4→5", color="red",
  story=[
    "Everything goes quiet. Masks, empty shelves, a closed sign on every door. The board drains of color and turns grey. It's the loneliest chapter in the game. The cat you made is the only company the programmer has, asleep on the windowsill in the background.",
    "The ★ is the closed sign flipped back to OPEN.",
  ],
  tracks=[
    dict(code="09a", tag="virus", title="The Virus", items=[
      ("Virus Particle", "about a ten-thousandth of a millimeter across. not quite alive. it can't do anything until it gets inside you."),
      ("Positive Test", "two lines."),
      ("Ambulance", "the sirens didn't stop for weeks."),
      ("Ventilator", "a machine, breathing for someone."),
    ]),
    dict(code="09b", tag="lockdown", title="The Lockdown", items=[
      ("Face Mask", "a thin layer between you and everyone else."),
      ("Hand Sanitizer", "sold out everywhere. people made it in their kitchens."),
      ("Toilet Paper", "the shelves were empty. nobody could really explain why."),
      ("Closed Sign", "cities that never slept went silent. you heard birds you'd never noticed before."),
      ("Video Call", "everyone you know in little boxes. 'you're on mute.'"),
      ("Vaccine Vial", "made in under a year, on decades of research nobody had heard of."),
    ]),
  ],
  final=("Open Sign ★", "Ventilator + Vaccine Vial",
         "the sign flipped back. you were still here. that counts for something."),
  companion="The cat on the windowsill and the companion <strong>blink at the same moment</strong>, every time. The game never points it out.",
  facts=[("violet", "Loop 2 only — companion note, the first time they blink together",
    "<span class='mono'>\"two particles can be entangled. measure one and you instantly know the other, no matter how far apart they are. einstein called it spooky action at a distance.\"</span>")],
),
dict(
  key="c10", num="Ch10", title="War + Freedom", time=55, stage="Stage 5 · split board", color="red",
  story=[
    "The only split board in the game. War runs on one side and Freedom on the other, and the player merges both at once: destruction next to resistance. The items come from images that exist right now, this year. The game doesn't pick a side. It merges.",
    "The ★ is a map with the borders redrawn.",
  ],
  tracks=[
    dict(code="10a", tag="war", title="War", items=[
      ("Soldier", "usually young. usually sent by someone who isn't going."),
      ("Tank", "sixty tons of steel that can drive through a house."),
      ("Drone", "the pilot might be on another continent, home in time for dinner."),
      ("Missile", "it takes seconds."),
      ("Bombed Hospital", "under the laws of war, a hospital is never supposed to be a target."),
      ("Body", "a civilian. the silhouette could be anyone."),
      ("Rubble", "someone's kitchen is in there somewhere."),
      ("Refugee", "one small bag. what would you grab?"),
      ("Tent", "temporary, for years."),
      ("Aid Crate", "food falling from the sky. never enough."),
      ("Memorial", "stone, so no one forgets. people forget anyway."),
    ]),
    dict(code="10b", tag="freedom", title="Freedom", items=[
      ("Constitution", "rights, written down. a promise on paper."),
      ("Newspaper", "someone whose job is to say what happened."),
      ("Protest Sign", "cardboard and marker. the oldest social media."),
      ("Megaphone", "one voice, loud enough for a crowd."),
      ("Police Lights", "red and blue on the ceiling."),
      ("Raised Fist", "2020. possibly the largest protest movement in american history."),
      ("Ceasefire Sign", "one word, painted by people who never fired anything."),
      ("Ballot Box", "one paper, one vote. people died so you could fold it and drop it in."),
    ]),
  ],
  final=("Redrawn Map ★", "Memorial + Ballot Box",
         "the same world with the borders redrawn. again."),
  companion="See <strong>The companion in the war</strong> below.",
  facts=[("red", "The companion in the war",
    "<strong>1. It covers its eye.</strong> When the Bombed Hospital is made, the companion slowly lifts two of its cables and wraps them over its eye. It stays like that and keeps floating, but it can't watch. It's the only time in the game it looks away from you.<br><br>"
    "<strong>2. The board keeps the scars.</strong> Every cell where a War item is merged is left with a faint scorch mark. The marks <em>stay for the rest of the loop</em>, under the Death board, the Unraveling board and the last chapter. You can't clean them.<br><br>"
    "<strong>3. The music stops.</strong> From the Bombed Hospital until the Memorial there's no soundtrack, only the taps and merge sounds. The player hears their own hands.<br><br>"
    "<strong>4. It looks.</strong> When the Memorial is made, the cables come down. Its eye doesn't look at you. It looks at the Memorial, and stays there until the chapter ends."),
    ],
),
dict(
  key="c11", num="Ch11", title="Death", time=30, stage="Stage 5–6", color="red",
  story=[
    "The void turns white. The programmer is caring for someone they love, and losing them. The chapter never says who, because the player fills that in. One track is the hospital room. The other is the things they leave behind.",
    "After this, the programmer wants out of the world. Everything that follows is a response to this chapter.",
  ],
  tracks=[
    dict(code="11a", tag="the room", title="The Room", items=[
      ("Get Well Card", "everyone signed it. nobody knew what to write."),
      ("Flowers", "the nurses let you keep them by the window."),
      ("Hospital Bed", "the rails go up at night."),
      ("IV Drip", "drop by drop. you count them without meaning to."),
      ("Heart Monitor", "you learn the sound. then you learn to listen for it stopping."),
      ("Flatline", "hearing may be one of the last senses to go. you kept talking."),
    ]),
    dict(code="11b", tag="keepsakes", title="What's Left", items=[
      ("Photograph", "the version of them you want to keep."),
      ("Reading Glasses", "still folded on the nightstand."),
      ("Their Sweater", "it still smells like them. for a while."),
    ]),
  ],
  final=("Gravestone ★", "Flatline + Their Sweater",
         "no name. no date. you know who it is."),
  companion="Present and still. Its eye doesn't blink once for the whole chapter. After Gravestone ★ there are three seconds of silence, then the board fades.",
),
dict(
  key="c12", num="Ch12", title="The Unraveling", time=45, stage="Stage 6", color="dim",
  story=[
    "A person coming apart on one side of the board, and a machine being built on the other. The programmer is trying to escape the world, and also trying to stay in it forever.",
    "When the escape track bottoms out, a brain appears on the board. Nobody tapped for it. Wiring it up is the upload.",
  ],
  tracks=[
    dict(code="12a", tag="escape", title="The Escape", items=[
      ("Tea", "caffeine and warm hands. the gentlest escape."),
      ("Coffee", "caffeine blocks the chemical that tells your brain it's tired. you're still tired. you just can't feel it."),
      ("Energy Drink", "a few cups of coffee in a can that looks like a toy."),
      ("Cigarette", "nicotine reaches the brain in about ten seconds."),
      ("Vape", "the same thing. it smells like mango."),
      ("Joint", "time stretches. the song means something now."),
      ("Mushrooms", "psilocybin quiets the part of the brain that keeps telling you who you are."),
    ]),
    dict(code="12b", tag="machine", title="The Machine", items=[
      ("Wire", "copper. a signal moving at a good fraction of the speed of light."),
      ("Circuit Board", "a city again. roads for electrons."),
      ("Chip", "billions of transistors on a sliver of silicon the size of a fingernail."),
      ("Processor", "it does one simple thing billions of times a second."),
      ("Neural Link", "electrodes thinner than a hair, listening to neurons as they fire."),
      ("Brain Scanner", "it maps every connection. the first creature ever fully mapped was a worm."),
    ]),
    dict(code="12c", tag="upload", title="The Upload", items=[
      ("Brain", "about 86 billion neurons. the worm had 302."),
    ]),
  ],
  final=("Brain with Wires ★", "Brain + Brain Scanner",
         "a mind, connected. it can be read. maybe it can be copied. the signal coming off it is shaped like a worm."),
  companion="When <strong>Mushrooms</strong> is made, the board edges glitch and a <strong>Brain</strong> appears. The companion placed it, and its eye stays on it. Brain + Brain Scanner → Brain with Wires ★. Then the board goes dark.",
  facts=[("violet", "Loop 2 only — companion note, just before Brain with Wires ★",
    "<span class='mono'>\"Matthew Nagle was paralyzed from the neck down. In 2004, they placed 96 electrodes into his motor cortex — a chip smaller than an aspirin. He moved a cursor across a screen using only his thoughts. He played Pong. He changed the channel on his television. He died three years later. The chip outlived him.\"<br><span class='dim'>[pause]</span><br>\"someone kept the data.\"</span>")],
),
dict(
  key="archive", num="Hidden", title="The Archive", time=25, stage="Stage 6 · Loop 2+ only", color="violet", hidden=True,
  story=[
    "<strong>Only in Loop 2 or later, and only after ten connections with Neuron 303</strong> (section 04). It plays straight after Brain with Wires ★ and the line \"someone kept the data.\"",
    "This is the lab where the cat came from. The ten lab logs have already told the player the story in pieces, and now they walk through the building. The game still never says whose cat it was.",
  ],
  tracks=[
    dict(code="H-a", tag="the lab", title="The Lab", items=[
      ("Lab Coat", "a name tag with the name scratched off."),
      ("Keycard", "level 3. the door at the end of the hall."),
      ("Cage", "clean. labeled. a water bottle, half full."),
      ("Operating Table", "sterile, white, too big for what's lying on it."),
      ("The Implant", "96 electrodes, smaller than an aspirin. it recorded every signal it could hear."),
    ]),
    dict(code="H-b", tag="the records", title="The Records", items=[
      ("Consent Form", "signed by someone. not by the one it was about."),
      ("Brain Scan", "a cat's brain, sliced into light."),
      ("Cassette Tape", "hours of signal. cats dream. this one did."),
      ("Hard Drive", "everything it ever thought, on one drive."),
      ("Storage Box", "unlabeled. shelf nine. nobody has opened it in years."),
    ]),
  ],
  final=("Sealed Box ★", "The Implant + Storage Box",
         "someone kept it. they never said why."),
  companion="Silent for the whole chapter. Its eye doesn't follow your taps here. It follows <strong>The Implant</strong>, wherever it is on the board.",
),
dict(
  key="c13", num="Ch13", title="The String", time=25, stage="Stage 6–7", color="violet",
  story=[
    "The uploaded mind rebuilds itself from the inside. On one track, a blank computer screen boots back up: bits, code, a blinking cursor, a loading bar. On the other, a memory pieces itself together: a torn photo, a face, a name, a mirror. The player doesn't realize they're putting their own mind back together.",
    "The last item is the smallest thing physics has imagined, a vibrating string. It looks exactly like the <strong>Spark</strong> from Ch1, except one pixel is wrong.",
  ],
  tracks=[
    dict(code="13a", tag="boot", title="Reboot", items=[
      ("Bit", "one or zero. everything you are could be written in these."),
      ("Byte", "eight bits. enough for one letter."),
      ("Line of Code", "an instruction. something is writing you back."),
      ("Cursor", "blinking. waiting for the next thing you'll be."),
      ("Window", "a program that's running right now. is this one you?"),
      ("Loading Bar", "almost there. it's been almost there for a long time."),
    ]),
    dict(code="13b", tag="memory", title="Memory", items=[
      ("Torn Photo", "a piece of a memory. you're not sure whose."),
      ("Faded Photo", "every time you remember something, you rebuild it. it comes out a little different each time."),
      ("Face", "you know this face. you can't place it."),
      ("Name Tag", "yours. you'd almost forgotten."),
      ("Mirror", "the part of you that says 'i'. nobody has found where it lives."),
    ]),
  ],
  final=("The String ★", "Loading Bar + Mirror",
         "string theory says the smallest thing in the universe is a tiny vibrating string. this one looks exactly like the spark that started everything. except for one pixel."),
  companion="Loop 1: silent all chapter, eye on you. Then, after The String ★, it speaks for the first and only time in Loop 1 (below).",
  facts=[("violet", "Loop 2 only — companion note, when Ch13 opens",
    "<span class='mono'>\"there are about 200 people in storage right now. legally dead. frozen in liquid nitrogen at -196 degrees. waiting for a technology that doesn't exist yet. they signed papers before they died. they believed someone would find the pattern inside and run it again.\"<br><span class='dim'>[three seconds]</span><br>\"the pattern is never exactly the same when it runs again. one pixel. one memory that isn't where it was.\"<br><span class='dim'>[pause]</span><br>\"they knew that. they signed anyway.\"</span>")],
),
]

MUTATION_LOGS = [
  "DAY 1 — subject arrived. adult cat. calm. no name on the paperwork.",
  "DAY 3 — implant surgery complete. 96 electrodes. subject recovering.",
  "DAY 9 — signal is clean. we can watch it dream.",
  "DAY 20 — subject purrs when the recording starts. readings spike every time. no explanation.",
  "DAY 41 — subject watches the observation window for hours. it watches us.",
  "DAY 60 — funding cut. study closes at the end of the month.",
  "DAY 61 — door found open this morning. subject gone.",
  "DAY 62 — searched the grounds. nothing. do not report.",
  "DAY 200 — the implant is still transmitting. it's inside a house somewhere. someone is feeding it.",
  "DAY 4,017 — signal stopped. someone should keep the data.",
]
